name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: "Test and lint for Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.7.1", "3.8.0", "3.9.0", "3.10.0", "3.11.0", "3.12.0", "3.13.0"]

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox tox-gh-actions
      - name: "Run tests for ${{ matrix.python-version }}"
        run: tox -e test_package
      - name: "Run linters (isort, black, mypy and flake8) for ${{ matrix.python-version }}"
        run: tox -e lint
